### ISSUE TITLE
find modern C++ replacement for atoi

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/processtree-cpp#9]
std::stoi

**Comment by klaeufer** [comment]
need to double-check performance of stoi vs. atoi

**Comment by gkthiruvathukal** [comment]
The man page for atoi() suggests:

The atoi() and atoi_l() functions are thread-safe and async-cancel-safe.
The strtol() and strtol_l() functions are recommended instead of atoi() and atoi_l() functions, especially in new code.

I think your choice for C++ is equivalent to this guidance. Apparently, they even have these same names in standard C++.
The performance differences should be negligible (hopefully).  I'll probably replace the version used in the C version based on your final decision.

**Comment by klaeufer** [comment]
atoi and stoi seem to be equally performant
